# Profession family knowledge (client-facing). {label}=topic label, {noun}/{nouns}=profession.
F = {}

F['vet'] = dict(
 noun='vet', nouns='vets', practice='veterinary practice', hub='vets', group='healthcare',
 regulator=[
  "Every vet practising in the UK must be registered with the Royal College of Veterinary Surgeons (RCVS), and you can search the RCVS register by name before you book. Veterinary nurses have their own RCVS register too. Many practices also join the voluntary RCVS Practice Standards Scheme, which inspects premises, equipment and clinical processes.",
  "Some vets hold further qualifications such as an RCVS certificate, advanced practitioner status or specialist status in a particular species or discipline. If your animal has a complex or unusual condition, it is reasonable to ask whether the vet treating it holds one of these, or whether they refer to someone who does.",
 ],
 scenarios=["a new puppy or kitten needing vaccinations, microchipping and a first health check","an older pet with stiffness, weight loss or changes in appetite","an injury after a fall, fight or road accident","dental problems such as bad breath, broken teeth or difficulty eating","a pet that has eaten something toxic or unusual","ongoing management of a condition like diabetes, arthritis or skin allergies","neutering, minor surgery or a second opinion before major surgery","travel paperwork or end-of-life care planning"],
 prepare=["your animal's age, breed or species and approximate weight","any vaccination and microchip records you have","a list of current medication, supplements and diet","when symptoms started and whether they are getting worse","photos or short videos of the behaviour or symptom","your pet insurance policy details, if you have cover","how far you can travel and whether you need home visits","the times you are available for appointments"],
 questions=["Who will actually examine my animal, and what experience do they have with this species?","Do you provide your own out-of-hours cover or use a separate emergency provider?","Can you give me a written estimate before any treatment goes ahead?","Do you offer payment plans or claim directly from my insurer?","What diagnostic equipment do you have on site, and what do you refer out?","How do you handle follow-up checks and repeat prescriptions?","Are you part of the RCVS Practice Standards Scheme?","Who should I call if my pet gets worse overnight?"],
 fees=["Veterinary fees vary a great deal between practices, regions and ownership groups, and the CMA has looked closely at transparency in this market. A good practice will explain the consultation charge, any likely tests and the range of treatment options before you commit. Because every case is different, iComply does not publish prices: quotes come from the practice and are POA.","Ask for an itemised estimate for anything beyond a routine consultation, and ask whether written prescriptions are available if you would prefer to buy medication elsewhere. Insurers often require you to pay first and claim later, so check your policy's excess and limits."],
 red_flags=["pressure to agree to expensive treatment without a clear explanation of alternatives","no way to see who is registered with the RCVS at the practice","vague answers about who covers emergencies at night and at weekends","refusal to provide a written estimate or prescription when asked","no clear plan for follow-up after surgery or treatment"],
 timeline="Routine appointments are often available within days, though busy practices can book further ahead. Emergencies should never wait for a matching service: if your animal is in immediate danger, phone the nearest open practice or emergency vet straight away. For planned care, we aim to put you in touch with a practice that has capacity in a sensible travelling distance.",
 after="Once you are introduced, the practice registers your animal, books the appointment and owns the clinical relationship. Your records stay with them, and you can move to a different practice later if you wish. We may check in briefly to make sure the introduction was useful.",
 faqs=[("Can you help in an animal emergency?","If your animal is in immediate danger, do not wait for an enquiry reply. Phone your nearest open veterinary practice or out-of-hours emergency vet now. Our service is for finding a practice for planned or ongoing care."),("Do I need to register with a vet before my pet is ill?","It is sensible to register in advance. Registration means the practice has your details and history on file, which saves time if something goes wrong.")],
)

F['accountant'] = dict(
 noun='accountant', nouns='accountants', practice='accountancy practice', hub='accountants', group='accountancy',
 regulator=[
  "In the UK, the word \"accountant\" on its own is not a protected title, so anyone can use it. Titles such as Chartered Accountant (ICAEW, ICAS or Chartered Accountants Ireland), Chartered Certified Accountant (ACCA) and Chartered Management Accountant (CIMA) are protected, and members are bound by their body's ethics, training and complaints rules. Only registered auditors can sign statutory audit reports.",
  "Every practice offering accountancy services must also be supervised for anti-money-laundering purposes, either by a professional body or by HMRC. It is reasonable to ask which body supervises a firm, whether they hold professional indemnity insurance, and how complaints are handled.",
 ],
 scenarios=["a sole trader filing a first Self Assessment return","a new limited company needing year-end accounts and a corporation tax return","a landlord with rental income from one or several properties","a contractor deciding how to work and how to pay themselves","a growing business that needs management accounts and cash-flow forecasting","someone behind on filings who needs to catch up with HMRC","a VAT registration or a change of VAT scheme","a business sale, restructure or investment round that needs proper numbers"],
 prepare=["the type of business or income you have (sole trader, partnership, company, landlord, employee)","your Unique Taxpayer Reference or company number","rough annual turnover or income range","which software you use, if any (for example Xero, QuickBooks or Sage)","the deadlines you know about and any letters from HMRC","whether you are VAT registered or close to the threshold","how often you want contact: once a year or monthly","the services you think you need, even if you are unsure"],
 questions=["Are you a member of a professional body, and which one?","Who will actually prepare my accounts, and who reviews them?","Is your fee fixed for the year or based on time spent?","What is included, and what would be charged as extra work?","How do you handle Making Tax Digital requirements?","How quickly do you usually reply to emails and calls?","Do you have experience with businesses or income like mine?","What do you need from me each month or each year?"],
 fees=["Accountancy fees depend on the complexity of your affairs, the quality of your records and how much of the work you want the accountant to take on. Many practices offer fixed monthly or annual packages; others charge for time. Either can be fair if the scope is written down. iComply does not set or publish fees: the practice will quote you, and that quote is POA.","Ask for an engagement letter before work starts. It should list what is included, your responsibilities, deadlines and how extra work is charged. Comparing two or three written scopes is usually more useful than comparing headline prices."],
 red_flags=["no engagement letter or written scope before work begins","promises of tax savings that sound too good to be true","reluctance to say which professional body or AML supervisor they use","no clear answer about who handles your file day to day","pressure to sign up to schemes you do not understand"],
 timeline="Most practices can take on a new client within a few weeks, but capacity tightens sharply in the run-up to the 31 January Self Assessment deadline and around company year ends. If you have a deadline coming up, say so in your enquiry so we can prioritise practices with room to help now.",
 after="After the introduction, the practice will usually run its own onboarding: identity checks required under money-laundering rules, an engagement letter and authority to act with HMRC. From then on the relationship is between you and the accountant. You stay free to change firms later; a professional clearance letter makes handovers straightforward.",
 faqs=[("Do I need a chartered accountant?","Not always. For simple Self Assessment a qualified, supervised accountant may be enough. For audits, complex group structures or specialist tax work, a chartered or certified firm is often the safer choice. We can match you to either."),("Can I switch accountant part-way through the year?","Yes. Your new accountant will contact the old one for professional clearance and any information they need. Tell us your timing and we will match you with a practice that can take over smoothly.")],
)

F['bookkeeper'] = dict(
 noun='bookkeeper', nouns='bookkeepers', practice='bookkeeping service', hub='bookkeepers', group='accountancy',
 regulator=[
  "Bookkeeping is not a regulated title in the UK, but anyone providing bookkeeping services for a fee must be supervised for anti-money-laundering purposes, either by HMRC or by a professional body. Membership of the Institute of Certified Bookkeepers (ICB) or the Association of Accounting Technicians (AAT) shows a bookkeeper has trained to a recognised standard and agreed to a code of conduct.",
  "Ask whether a bookkeeper holds professional indemnity insurance and which body supervises them. Good bookkeepers are also clear about where their work stops and an accountant's starts, for example on year-end accounts and tax advice.",
 ],
 scenarios=["a small business owner who is behind on receipts and bank reconciliations","a sole trader preparing for Making Tax Digital quarterly updates","a company that needs VAT returns prepared and submitted on time","a business moving from spreadsheets to cloud software","an employer who wants payroll run each month","a landlord who wants rental income and costs kept tidy","a charity or club that needs clear records for trustees","a growing team that wants monthly management reports"],
 prepare=["which accounting software you use or would like to use","roughly how many bank transactions you have each month","whether you are VAT registered and which scheme you use","whether you run payroll and how many staff you have","how far behind the records are, if at all","how you currently keep receipts and invoices","whether you already have an accountant for year-end work","the reports you would like to see each month"],
 questions=["Which software are you certified or experienced in?","Are you supervised for anti-money-laundering, and by whom?","Do you work remotely, on site, or both?","How do you want me to send receipts and documents?","Is the fee based on transaction volume, hours or a fixed package?","Will you liaise with my accountant at year end?","What happens to my data if we stop working together?","How quickly can you catch up on any backlog?"],
 fees=["Bookkeeping is usually priced on volume and frequency: how many transactions, how many bank accounts and how often you want the books brought up to date. Catch-up work is often quoted separately. iComply does not publish prices; the bookkeeper you are matched with will give you a POA quote based on your records.","A short call where you share a sample month of transactions usually gives the bookkeeper enough to quote fairly. Ask for the scope in writing so you know what is covered."],
 red_flags=["no anti-money-laundering supervision","unclear access arrangements for your bank feeds and software","no written agreement about scope and deadlines","claims to give tax advice they are not qualified to give","no plan for handing records back if you part ways"],
 timeline="Many bookkeepers can start within one to two weeks. Clearing a large backlog takes longer and depends on how organised your paperwork is. If a VAT or payroll deadline is close, include it in your enquiry.",
 after="Once matched, the bookkeeper will set up access to your software and bank feeds, complete identity checks and agree a routine with you. You keep ownership of your records. We may follow up to check the introduction worked well.",
 faqs=[("What is the difference between a bookkeeper and an accountant?","A bookkeeper records day-to-day transactions and keeps your books accurate. An accountant typically prepares year-end accounts, tax returns and gives tax advice. Many businesses use both, and they work best when they talk to each other."),("Can a bookkeeper submit my VAT return?","Many can, through Making Tax Digital compatible software, once you authorise them. Check this is included in the scope before you start.")],
)

F['tax'] = dict(
 noun='tax adviser', nouns='tax advisers', practice='tax practice', hub='tax-advisors', group='accountancy',
 regulator=[
  "\"Tax adviser\" is not a protected title in the UK. The Chartered Institute of Taxation (CTA qualification) and the Association of Taxation Technicians (ATT) are the main specialist bodies, and many accountants and solicitors also advise on tax. Members of these bodies follow Professional Conduct in Relation to Taxation, a shared code covering honesty, confidentiality and dealing with HMRC.",
  "Tax advisers who provide services for a fee must be supervised for anti-money-laundering purposes. HMRC has also been tightening standards for paid tax agents, so it is reasonable to ask about qualifications, supervision and professional indemnity insurance before you go ahead.",
 ],
 scenarios=["a letter or enquiry from HMRC that needs a careful response","selling a property, shares or a business and wanting to understand the tax","income from overseas, or a move into or out of the UK","planning for inheritance tax across the family","a business considering investment schemes such as EIS or SEIS","a contractor unsure how IR35 applies to their work","a VAT question that could affect pricing or cash flow","a dispute or appeal against an HMRC decision"],
 prepare=["a short summary of the question or problem in your own words","copies of any HMRC letters, with reference numbers","the tax years involved","relevant figures, even if they are estimates","the names of any other advisers already involved","any deadlines given by HMRC or a buyer or seller","whether you want a one-off answer or ongoing support","your preferred way of meeting: online or in person"],
 questions=["Are you CTA or ATT qualified, or a member of another body?","Have you dealt with situations like mine before?","Will I get advice in writing that I can rely on?","How do you charge for initial advice and for ongoing work?","Will you deal with HMRC directly on my behalf?","What are the main risks or uncertainties in my position?","How long will this take, and what happens next?","Do you hold professional indemnity insurance?"],
 fees=["Tax advice is usually charged by time or as a fixed fee for a defined piece of work, such as a written report or handling an HMRC enquiry. Complexity, deadlines and the amount at stake all affect the quote. iComply does not publish fees; the adviser you are matched with will quote you, POA.","Ask whether the first conversation is free or chargeable, and ask for a written scope before detailed advice begins. If an HMRC enquiry is involved, ask whether you have fee protection insurance through an existing accountant."],
 red_flags=["schemes marketed as guaranteed or risk-free tax savings","pressure to act quickly without written advice","no professional body membership or AML supervision","advice that relies on keeping information from HMRC","fees linked to a percentage of tax \"saved\" without clear terms"],
 timeline="Straightforward questions can often be answered within a couple of weeks. HMRC enquiries and appeals have their own deadlines, which should be included in your enquiry so we can prioritise advisers with capacity. Large transactions benefit from advice before contracts are signed, not after.",
 after="Once introduced, the adviser will carry out identity checks, agree a written engagement and, where needed, get your authority to speak to HMRC. Advice and responsibility for it sit with the adviser, not with iComply.",
 faqs=[("Should I reply to HMRC before speaking to an adviser?","Note the deadline on the letter, but avoid sending a detailed reply before you have advice if the matter is complex. An adviser can often ask HMRC for more time where it is reasonable."),("Is tax planning legal?","Using reliefs and allowances as Parliament intended is normal and legal. Aggressive avoidance schemes are a different matter and can carry serious risks. A qualified adviser will explain the difference clearly.")],
)
