F = {}
_CQC = "Clinics carrying out regulated healthcare in England register with the Care Quality Commission (CQC); Wales, Scotland and Northern Ireland have their own regulators."
def _msk(noun, nouns, practice, hub, reg, body):
    return dict(noun=noun, nouns=nouns, practice=practice, hub=hub, group='healthcare', regulator=[reg, body],
 scenarios=["lower back pain after lifting or long periods of sitting","neck and shoulder tension linked to desk work","joint stiffness that limits walking or exercise","aches during or after pregnancy","sports-related strains and overuse problems","headaches that seem linked to posture or neck tension","recurring pain that has not settled with rest","an older relative who wants to stay active and mobile"],
 prepare=["where the pain is and how it started","how long it has been going on","anything that makes it better or worse","current medication and medical conditions","any scans or letters from your GP","whether you are pregnant","any treatment you have tried already","the days and times you can attend"],
 questions=["Are you registered with the statutory regulator, and can I check that online?","What will happen in the first appointment?","How many sessions do you expect I will need?","What exercises or advice will I get to do at home?","When would you suggest I see my GP instead?","Do you accept my health insurance?","What does treatment involve, and are there risks?","How will we know if it is working?"],
 fees=["Treatment is usually charged per session, with a longer first appointment for assessment. iComply does not publish prices; the practitioner quotes you, POA.","Be cautious about paying for long courses of treatment up front. A good practitioner will review progress regularly and tell you if another approach would suit you better."],
 red_flags=["no statutory registration","claims to treat conditions unrelated to muscles and joints","pressure to pay for many sessions in advance","no clear review of progress","discouraging you from seeing your GP"],
 timeline="Appointments are often available within a few days. Many people notice change within a few sessions, though longer-standing problems can take more time. Seek urgent medical help for severe pain after an accident, numbness around the groin, or loss of bladder or bowel control.",
 after="Once introduced, the practice will book your first appointment and agree a treatment plan with you. The practitioner is responsible for your care. iComply does not provide medical advice.",
 faqs=[("Do I need a referral?","No, you can usually book directly. Health insurers may need a GP referral before they pay."),("Is treatment painful?","Some techniques can feel uncomfortable, and you may feel sore for a day or two. Your practitioner should explain what to expect and adapt treatment to your comfort.")])
F['osteopath'] = _msk('osteopath','osteopaths','osteopathy clinic','osteopaths',
 "\"Osteopath\" is a protected title in the UK. Every osteopath must be registered with the General Osteopathic Council (GOsC), which sets standards and investigates concerns. You can check the GOsC register online before you book.",
 "Osteopaths use hands-on techniques such as massage, stretching and joint mobilisation, along with advice on exercise and posture. They assess your medical history first and should refer you to your GP if your symptoms need medical investigation.")
F['chiro'] = _msk('chiropractor','chiropractors','chiropractic clinic','chiropractors',
 "\"Chiropractor\" is a protected title in the UK. Every chiropractor must be registered with the General Chiropractic Council (GCC), which you can search online. Many are also members of the Royal College of Chiropractors or the British Chiropractic Association.",
 "Chiropractors focus on the spine, joints and muscles, using manual adjustment and mobilisation, plus exercise and lifestyle advice. Evidence is strongest for back and neck pain, and a careful chiropractor will be honest about what they can and cannot help with.")
F['podiatrist'] = _msk('podiatrist','podiatrists','podiatry clinic','podiatrists',
 "\"Podiatrist\" and \"chiropodist\" are protected titles. Practitioners must be registered with the Health and Care Professions Council (HCPC), and you can check the register online. Many are members of the Royal College of Podiatry.",
 "Podiatrists diagnose and treat problems with the feet and lower limbs, from ingrown toenails and verrucas to heel pain, gait problems and diabetic foot care. Some carry out nail surgery under local anaesthetic.")
F['podiatrist']['scenarios'] = ["heel pain such as plantar fasciitis","ingrown toenails or thickened nails","corns, calluses and hard skin","verrucas and fungal nail infections","foot care for people with diabetes","gait or running problems that cause knee or hip pain","custom insoles or orthotics","children's foot development worries"]
F['optician'] = dict(noun='optician', nouns='opticians', practice='opticians practice', hub='opticians', group='healthcare',
 regulator=["Optometrists and dispensing opticians must be registered with the General Optical Council (GOC), which you can check online. Optometrists carry out eye examinations; dispensing opticians fit and supply glasses and, with extra training, contact lenses.","Some optometrists hold extra qualifications that let them manage more eye conditions or prescribe certain medicines. In many areas of the UK, community optometrists provide minor eye condition and urgent eye care services."],
 scenarios=["a routine eye test or a new prescription","blurred vision, headaches or eye strain","a red, sore or sticky eye","new floaters or flashes of light","contact lens fittings and aftercare","children's eye tests","monitoring for glaucoma, diabetes or macular changes","choosing frames and lenses for work or sport"],
 prepare=["your current glasses or contact lenses","the date of your last eye test","any eye symptoms and when they started","medication and general health conditions","family history of glaucoma or other eye conditions","whether you drive or use screens for long periods","whether you are entitled to a free NHS eye test","your preferred appointment times"],
 questions=["Is the optometrist GOC registered?","What does the eye examination include?","Do you offer OCT or retinal imaging, and is it extra?","How much choice is there in frames and lenses?","Can I take my prescription elsewhere?","Do you provide urgent eye care appointments?","How do contact lens aftercare plans work?","What happens if I cannot get used to new glasses?"],
 fees=["Eye test fees vary, and many people qualify for free NHS sight tests, including children, people over 60 and some people with certain conditions or benefits. Glasses and contact lenses are priced separately. iComply does not publish prices; the practice quotes you, POA.","Ask whether advanced imaging is included and what the guarantee covers on glasses."],
 red_flags=["no GOC registration","refusal to give you your prescription","pressure to buy expensive lens upgrades","no proper check of eye health","no aftercare for contact lens wearers"],
 timeline="Routine eye tests can often be booked within a few days. Sudden loss of vision, a curtain over your vision, or severe eye pain needs urgent same-day assessment at an eye casualty or urgent eye service.",
 after="Once introduced, the practice will book your appointment. The optometrist is responsible for your eye care. iComply does not provide clinical advice.",
 faqs=[("How often should I have an eye test?","Usually every two years for adults, or more often if your optometrist recommends it, for example if you have diabetes or a family history of glaucoma."),("Do I have to buy glasses where I have my eye test?","No. You are entitled to a copy of your prescription and can buy glasses anywhere.")])
F['audiologist'] = dict(noun='audiologist', nouns='audiologists', practice='hearing clinic', hub='audiologists', group='healthcare',
 regulator=["Hearing aid dispensers must be registered with the Health and Care Professions Council (HCPC), and you can check the register online. Clinical audiologists may also be registered through the Academy for Healthcare Science or other recognised registers. Many are members of the British Society of Audiology or the British Society of Hearing Aid Audiologists.","If you have sudden hearing loss, pain, discharge or hearing loss in one ear only, you should see a doctor promptly, as some causes need medical treatment."],
 scenarios=["difficulty following conversations in noisy places","turning the television up louder than others like","ringing or buzzing in the ears (tinnitus)","a hearing test for work or peace of mind","earwax that keeps blocking the ears","reviewing or replacing existing hearing aids","a child with suspected hearing problems","protecting hearing for music or noisy work"],
 prepare=["when you first noticed hearing changes","whether one or both ears are affected","any tinnitus, dizziness or pain","history of noise exposure","current hearing aids, if any","medication and medical history","whether a family member can come with you","your daily listening situations"],
 questions=["Are you HCPC registered?","What does the hearing test involve, and is it free?","Do you sell hearing aids from many manufacturers or a few?","What aftercare is included with hearing aids?","Do you offer a trial period?","Do you provide wax removal?","When would you refer me to my GP or an ENT doctor?","How are repairs and batteries handled?"],
 fees=["Hearing tests are sometimes free with private providers, while hearing aids vary widely depending on technology and aftercare. Hearing aids are also available through the NHS. iComply does not publish prices; the clinic quotes you, POA.","Ask what aftercare, servicing and trial period are included, and compare whole-package costs rather than device prices alone."],
 red_flags=["no HCPC registration","high-pressure sales on the same day as your test","no trial period or aftercare","no referral when red-flag symptoms are present","unclear warranty terms"],
 timeline="Private hearing tests are often available within a week. Fitting hearing aids may take a second appointment. Sudden hearing loss needs urgent medical assessment, ideally within days.",
 after="Once introduced, the clinic will book your hearing assessment. The audiologist is responsible for your care. iComply does not provide clinical advice.",
 faqs=[("Can I get hearing aids on the NHS?","Yes, with a GP referral. Private providers offer more choice of devices and often shorter waits."),("Does a hearing test hurt?","No. It usually involves listening to sounds through headphones and a look inside the ears.")])
F['counsellor'] = dict(noun='counsellor', nouns='counsellors', practice='counselling practice', hub='private-therapy', group='healthcare',
 regulator=["\"Counsellor\" and \"psychotherapist\" are not protected titles in the UK. To protect yourself, choose a practitioner on a register accredited by the Professional Standards Authority, such as BACP, UKCP or NCPS. Practitioner psychologists, who use titles such as clinical or counselling psychologist, must be registered with the HCPC.","Accredited registers require training, supervision, a code of ethics and a complaints procedure. A good therapist will explain their approach, confidentiality and its limits in the first session."],
 scenarios=["persistent anxiety, worry or panic","low mood or depression","grief after a death or loss","relationship difficulties or separation","stress and burnout at work","a past trauma that still affects daily life","problems with alcohol, drugs or other habits","support for a child or teenager"],
 prepare=["what you would like help with, in a sentence or two","how long you have been feeling this way","whether you prefer in-person, video or phone sessions","any preference for a practitioner's gender or background","whether you have tried therapy before and what helped","any medication or current support from your GP","your availability, including evenings","your budget expectations, so the practitioner can be honest about fit"],
 questions=["Which accredited register are you on?","What kind of therapy do you offer, and how does it work?","How long are sessions, and how many might I need?","What are your confidentiality rules?","Do you have experience with problems like mine?","What happens if I need to cancel?","Do you offer a short introductory call?","How will we review whether therapy is helping?"],
 fees=["Private therapy is usually charged per session. Fees vary with the therapist's training, experience and location, and some offer reduced rates for people on lower incomes. iComply does not publish prices; the therapist quotes you, POA.","Free talking therapies are also available through the NHS in England, and some employers offer support through an employee assistance programme. Ask your GP or HR team."],
 red_flags=["no membership of an accredited register","promises of a quick cure","pressure to commit to many sessions","blurred professional boundaries or contact outside sessions","no clear explanation of confidentiality"],
 timeline="Many private therapists can offer a first session within one to two weeks. If you are thinking about harming yourself or feel unsafe, call 999, go to A&E, or contact NHS 111 or Samaritans on 116 123 straight away.",
 after="Once introduced, the therapist will usually offer a short call or first session to see whether you work well together. Therapy is confidential between you and them. iComply does not provide therapy or medical advice.",
 faqs=[("What is the difference between counselling and psychotherapy?","The terms overlap. Counselling often focuses on a specific problem over a shorter period, while psychotherapy may explore deeper patterns over a longer time. A good practitioner will explain their approach."),("Can I get therapy on the NHS?","Yes. In England you can refer yourself to NHS Talking Therapies. Waiting times vary by area, which is why some people choose private therapy.")])
F['assessment'] = dict(noun='assessment clinic', nouns='assessment clinics', practice='specialist assessment service', hub='private-therapy', group='healthcare',
 regulator=["Diagnostic assessments for conditions such as ADHD and autism should be carried out by suitably qualified clinicians: psychiatrists registered with the GMC, practitioner psychologists registered with the HCPC, or multidisciplinary teams that follow NICE guidance. " + _CQC,
 "If you hope your NHS GP will prescribe medication after a private diagnosis, ask in advance whether they will agree to a shared care arrangement. Policies differ between areas and practices."],
 scenarios=["an adult who has long struggled with focus, organisation or restlessness","a child whose school has raised concerns","an adult wondering whether autism explains lifelong differences","long NHS waiting lists for assessment","needing a report to support adjustments at work or school","reviewing medication after diagnosis","family members wanting to understand a diagnosis","a second opinion on a previous assessment"],
 prepare=["a short description of the difficulties and when they began","school reports or comments from teachers, if available","input from family members or a partner","any previous assessments or reports","current medication and health conditions","your GP's details","whether you need a report for work or education","your availability for longer appointments"],
 questions=["Who will carry out the assessment, and how are they registered?","Does your process follow NICE guidance?","What does the fee include: assessment, report and follow-up?","How long is the wait for an appointment and for the report?","Will my GP accept your diagnosis for shared care?","Do you offer medication titration and reviews?","Is the assessment in person or online?","What support do you offer after diagnosis?"],
 fees=["Private assessments are usually charged as a package for the assessment and written report, with medication titration and reviews often charged separately. iComply does not publish prices; the clinic quotes you, POA.","In England, the NHS Right to Choose scheme may let some patients choose an alternative provider for assessment, with a GP referral. Ask your GP whether it applies."],
 red_flags=["clinicians whose registration you cannot check","very short assessments with no history or third-party input","guaranteed diagnoses","no clear aftercare or medication monitoring","unclear charges for reports"],
 timeline="Private waiting times range from a few weeks to several months depending on demand. Reports usually follow within a few weeks of the assessment.",
 after="Once introduced, the clinic will explain its process, send any questionnaires and book the assessment. Clinical responsibility sits with the assessing clinician. iComply does not provide medical advice.",
 faqs=[("Will a private diagnosis be recognised?","A thorough assessment by a properly qualified clinician should be. Shared care for medication depends on your GP's agreement, so ask them before booking."),("Can adults be assessed?","Yes. Many people are diagnosed in adulthood, and adult assessment services are widely available.")])
