F = {}
_CQC = "Private clinics providing regulated healthcare in England must register with the Care Quality Commission (CQC), which inspects and publishes ratings. In Wales the regulator is Healthcare Inspectorate Wales, in Scotland Healthcare Improvement Scotland, and in Northern Ireland the RQIA."
F['gp'] = dict(
 noun='private GP', nouns='private GPs', practice='private GP clinic', hub='private-gps', group='healthcare',
 regulator=[
  "Every doctor practising in the UK must be registered and hold a licence to practise with the General Medical Council (GMC). GPs also appear on the GMC's GP register. You can search the GMC's online register by name. " + _CQC,
  "A private GP does not replace your NHS GP. Good private clinics will ask for consent to share consultation notes with your NHS practice, so your records stay complete and medication is prescribed safely.",
 ],
 scenarios=["a quick appointment when an NHS slot is weeks away","a longer consultation to talk through several symptoms","a referral letter to a private specialist or for a scan","travel vaccinations or a fit-to-fly certificate","a health check, blood tests or screening","a sick note, medical report or occupational health assessment","ongoing support with a long-term condition alongside the NHS","a video consultation for someone who cannot easily travel"],
 prepare=["a short list of your symptoms and when they started","current medication, doses and any allergies","your NHS GP practice details","any recent test results or hospital letters","your private medical insurance details, if you have cover","whether you want a face-to-face or video appointment","the times you can attend","questions you want answered in the appointment"],
 questions=["Is the doctor GMC registered with a licence to practise?","Is the clinic registered with the CQC or the relevant regulator?","How long is a standard appointment?","What do tests, prescriptions and referral letters cost on top?","Will you share notes with my NHS GP?","Can you refer me to a private specialist, and do you have preferred consultants?","Do you accept my health insurance?","Who do I contact if I have questions after the appointment?"],
 fees=["Private GP fees usually depend on appointment length, the time of day and whether you are seen in person or by video. Prescriptions, blood tests, referral letters and certificates are often charged separately. iComply does not publish prices; the clinic quotes you, POA.","Ask for the full price of the appointment and any likely extras before you book, and check whether your health insurance covers outpatient GP care."],
 red_flags=["a doctor you cannot find on the GMC register","no CQC (or equivalent) registration for the clinic","reluctance to share information with your NHS GP","prescribing high-risk medicines without proper checks","unclear charges for tests and prescriptions"],
 timeline="Many private GP clinics offer same-day or next-day appointments, including evenings and weekends, and video appointments can be quicker still. If you have chest pain, difficulty breathing, signs of a stroke or another emergency, call 999 instead.",
 after="Once introduced, the clinic will register you, confirm your appointment and explain its terms. The doctor is responsible for your clinical care. iComply does not provide medical advice.",
 faqs=[("Will a private GP share my notes with my NHS GP?","With your consent, most do, and it is safer for you. Joined-up records help avoid duplicate tests and medication clashes."),("Can a private GP prescribe medication?","Yes, a GMC-registered doctor can issue private prescriptions. You pay the clinic's prescription fee and the pharmacy's price for the medicine.")],
)
F['specialist'] = dict(
 noun='private consultant', nouns='private consultants', practice='private hospital or clinic', hub='private-healthcare', group='healthcare',
 regulator=[
  "Hospital consultants should appear on the GMC's specialist register for their field, which you can check online. " + _CQC + " Private hospitals in England may also share outcomes data through the Private Healthcare Information Network (PHIN).",
  "Many private specialists also work in the NHS. If you have private medical insurance, your insurer may require a GP referral and may limit you to certain consultants or hospitals, so check before you book.",
 ],
 scenarios=["a long NHS waiting list for a first specialist appointment","a second opinion on a diagnosis or treatment plan","a scan or test to get answers sooner","planned surgery at a time that suits you","ongoing review of a long-term condition","a GP referral that you would like to use privately","insurance cover that requires an approved consultant","a family member who needs support with appointments"],
 prepare=["a GP referral letter, if you have one","your symptoms, history and current medication","any previous scans, results or hospital letters","your insurance policy number and authorisation code, if insured","whether you are self-paying","how far you can travel for appointments and treatment","any dates you cannot attend","questions about recovery and time off work"],
 questions=["Is the consultant on the GMC specialist register for this area?","How many of these procedures or assessments do they carry out?","What is included in the quoted package, and what is not?","What happens if there are complications or I need to stay longer?","Who looks after me after I leave the hospital?","Does my insurer recognise this consultant and hospital?","What are the alternatives, including waiting for NHS treatment?","What recovery time should I plan for?"],
 fees=["Private specialist care is often charged as separate consultation, test and treatment fees, or as a fixed-price package for a procedure that covers hospital stay and aftercare. What is included varies widely. iComply does not publish prices; the hospital or consultant quotes you, POA.","Ask whether a package includes follow-up appointments, physiotherapy and treatment of complications, and ask for the quote in writing."],
 red_flags=["a consultant not on the GMC specialist register for the treatment","no clear written quote or package terms","pressure to decide on surgery at the first appointment","no explanation of risks and alternatives","unclear arrangements for aftercare"],
 timeline="Private outpatient appointments can often be arranged within days or a few weeks. Surgery dates depend on assessment, any tests needed and theatre availability. Always seek urgent NHS care for emergencies.",
 after="Once introduced, the clinic or hospital will confirm the appointment and any referral or insurance requirements. Clinical responsibility lies with the consultant and the provider. iComply does not provide medical advice.",
 faqs=[("Do I need a GP referral to see a private consultant?","Self-paying patients can sometimes book directly, but many consultants prefer a referral, and insurers usually require one. A private GP can provide one quickly."),("Can I switch back to the NHS after a private consultation?","Yes. You can move between private and NHS care, though you may need to rejoin an NHS waiting list for treatment. Ask your GP how this works locally.")],
)
F['dentist'] = dict(
 noun='private dentist', nouns='private dentists', practice='dental practice', hub='private-dentists', group='healthcare',
 regulator=[
  "Dentists, dental hygienists, dental therapists and dental nurses must be registered with the General Dental Council (GDC), and you can check the GDC register online. Specialist titles such as orthodontist or endodontist can only be used by people on a GDC specialist list. " + _CQC,
  "If something goes wrong with private dental treatment, start with the practice's complaints process. The Dental Complaints Service can help with private dental complaints that are not resolved.",
 ],
 scenarios=["registering with a dentist after moving to a new area","toothache, swelling or a broken tooth","a routine check-up and hygiene appointment","replacing missing teeth with implants, a bridge or dentures","straightening teeth with braces or clear aligners","improving the look of teeth with whitening, bonding or veneers","a nervous patient who needs extra time or sedation","children's dental care"],
 prepare=["what you need: check-up, pain, or a specific treatment","any pain, swelling or sensitivity and how long it has lasted","when you last saw a dentist","medical history and current medication","whether you want to pay per treatment or join a dental plan","any dental insurance you hold","whether you are anxious about treatment","times and days you can attend"],
 questions=["Is the dentist GDC registered, and do they have experience with this treatment?","Can I have a written treatment plan with costs before starting?","What are the alternatives, including not treating?","Do you offer payment plans or a membership plan?","Who handles emergencies out of hours?","What guarantees apply to crowns, implants or aligners?","How many appointments will this take?","Can I see before-and-after examples for cosmetic work?"],
 fees=["Private dental fees vary between practices and depend on the treatment, materials and dentist's experience. Practices should give you a written treatment plan with costs before starting anything beyond an examination. Many also offer monthly membership plans. iComply does not publish prices; the practice quotes you, POA.","Ask what is included in a quote, such as follow-up reviews and adjustments, and whether finance options are regulated credit agreements."],
 red_flags=["no written treatment plan or costs","a dentist you cannot find on the GDC register","pressure to agree to extensive cosmetic treatment","no discussion of risks or alternatives","unclear arrangements if something fails"],
 timeline="Many private practices can see new patients within days, and urgent pain can often be seen the same or next day. Longer courses of treatment such as implants or aligners take months. For swelling that affects breathing or swallowing, seek emergency care at once.",
 after="Once introduced, the practice will register you and book an examination, after which the dentist will propose a treatment plan. Clinical decisions are between you and the dentist. iComply does not provide dental advice.",
 faqs=[("Can I see a private dentist and stay with my NHS dentist?","Yes, you can use both. Some patients see a private dentist for specific treatments and keep NHS care for routine check-ups, if their NHS practice agrees."),("Do I need a check-up before treatment?","Almost always. A dentist needs to examine you, and often take X-rays, before recommending treatment.")],
)
F['physio'] = dict(
 noun='physiotherapist', nouns='physiotherapists', practice='physiotherapy clinic', hub='physiotherapists', group='healthcare',
 regulator=[
  "\"Physiotherapist\" and \"physical therapist\" are protected titles in the UK. Anyone using them must be registered with the Health and Care Professions Council (HCPC), and you can check the HCPC register online. Most physiotherapists are also members of the Chartered Society of Physiotherapy (CSP), shown by the letters MCSP.",
  "Sports therapists, massage therapists and personal trainers can be helpful for some needs, but they are not physiotherapists. For an injury, post-surgery rehabilitation or a neurological condition, check that you are booking an HCPC-registered physiotherapist.",
 ],
 scenarios=["a sports injury such as a sprain, strain or ligament tear","back or neck pain that is not settling","rehabilitation after joint replacement or other surgery","a frozen shoulder or other painful, stiff joint","rehabilitation after a stroke or with a neurological condition","work-related aches from desk or manual work","a child with a developmental or movement problem","an older relative who needs help with mobility at home"],
 prepare=["where it hurts and how the problem started","how long it has lasted and whether it is improving","any scans, X-rays or letters from your GP or surgeon","any operations you have had, with dates","what activities are affected, such as work or sport","your health insurance details, if you have cover","whether you would prefer clinic, home or video sessions","your goals, such as returning to running or walking without pain"],
 questions=["Are you HCPC registered, and do you have experience with this problem?","How long is the first assessment, and what will it involve?","How many sessions do you usually expect for problems like this?","Will I get exercises to do at home?","Do you work with my insurer?","When would you refer me back to my GP or a specialist?","Do you offer home visits or video sessions?","How will we measure progress?"],
 fees=["Physiotherapy is usually charged per session, with the first assessment often longer than follow-ups. Home visits, specialist neurological physiotherapy and sports rehabilitation programmes may be priced differently. iComply does not publish prices; the clinic quotes you, POA.","Ask whether your health insurer requires a GP referral or pre-authorisation, and whether the clinic bills the insurer directly."],
 red_flags=["no HCPC registration","a long block of prepaid sessions before any assessment","no home exercise plan or progress review","treatments promised to cure everything","no referral back when problems do not improve"],
 timeline="Private physiotherapy appointments are often available within a few days. Recovery time depends on the problem: some settle in a few sessions, while post-operative or neurological rehabilitation can take months. Sudden severe weakness, loss of bladder or bowel control, or numbness around the groin needs urgent medical help.",
 after="Once introduced, the clinic will book your assessment and agree a treatment plan with you. Clinical responsibility sits with the physiotherapist. iComply does not provide medical advice.",
 faqs=[("Do I need a GP referral for private physio?","No, you can usually book directly as a self-paying patient. Your insurer may require a referral, so check your policy."),("Can physio help if I have already had a scan?","Yes. Bring the report with you. A physiotherapist will combine it with their own assessment to plan treatment.")],
)
