F = {}
F['solicitor'] = dict(
 noun='solicitor', nouns='solicitors', practice='law firm', hub='solicitors-lawyers', group='legal',
 regulator=[
  "Solicitors in England and Wales are regulated by the Solicitors Regulation Authority (SRA), and you can check an individual or firm on the SRA's register. In Scotland solicitors are regulated by the Law Society of Scotland, and in Northern Ireland by the Law Society of Northern Ireland. Regulated firms must hold professional indemnity insurance and have a complaints procedure; if that does not resolve things, the Legal Ombudsman can look at service complaints in England and Wales.",
  "The word \"lawyer\" is not protected on its own, so check that whoever handles your matter is a solicitor, a chartered legal executive (CILEx) or another authorised professional. Reserved activities such as conducting court litigation and certain probate and conveyancing work can only be carried out by authorised people.",
 ],
 scenarios=["a dispute with an employer, landlord, business or neighbour","a separation, divorce or arrangements for children","buying or selling property, or a lease problem","a business contract, shareholder agreement or company sale","being contacted by the police or facing a criminal charge","an injury or a medical treatment that went wrong","a will, a lasting power of attorney or a family member's estate","a debt that is owed to you, or one you are being chased for"],
 prepare=["a short timeline of what has happened, with dates","the names of the other people or organisations involved","copies of key documents such as contracts, letters or court papers","any deadlines you have been given, especially court dates","what outcome you would like","whether you have legal expenses insurance (often in home or car policies)","whether you may be eligible for legal aid","how you prefer to be contacted"],
 questions=["Who will handle my matter day to day, and who supervises them?","How much experience do you have with cases like mine?","How will you charge: hourly, fixed fee, or another arrangement?","What is your realistic view of my options at this stage?","What are the likely next steps and timescales?","What could make costs rise, and how will you warn me?","How will you keep me updated?","What is your complaints procedure?"],
 fees=["Legal fees depend on the type of matter, its complexity and who does the work. Firms commonly charge hourly rates, fixed fees for defined stages, or (in some claims) conditional fee arrangements. Regulated firms in England and Wales must publish pricing information for certain services and give you clear costs information at the outset. iComply does not publish fees; the firm will give you a POA quote.","Ask for a written estimate and for an explanation of what is not included, such as court fees, barristers' fees or experts. Ask too whether legal expenses insurance or legal aid might cover some or all of the cost."],
 red_flags=["no clear costs information or client care letter","a firm or individual you cannot find on the relevant register","guarantees about the outcome of a dispute","pressure to sign immediately without time to read terms","requests to send money to an account that changes by email"],
 timeline="Many firms can arrange an initial conversation within a few days. Court deadlines, police interviews and limitation periods are time-critical, so include them in your enquiry. If you have a court hearing in the next few days, contact a solicitor directly as well as enquiring with us.",
 after="After the introduction, the firm will carry out identity checks and conflict checks and send a client care letter setting out who is acting for you, what they will do and how they charge. Your legal relationship is with the firm. iComply does not give legal advice and does not take part in your case.",
 faqs=[("Is a solicitor the same as a lawyer?","\"Lawyer\" is a general word that covers solicitors, barristers, chartered legal executives and others. A solicitor is a specific regulated professional who can advise you, run your case and instruct a barrister if needed."),("Can I get legal aid?","Legal aid is still available for some criminal, family (especially where there is domestic abuse), housing and immigration matters, subject to means and merits tests. A matched firm can tell you whether you are likely to qualify.")],
)
F['barrister'] = dict(
 noun='barrister', nouns='barristers', practice='barristers\' chambers', hub='barristers', group='legal',
 regulator=[
  "Barristers in England and Wales are regulated by the Bar Standards Board (BSB). You can check the Barristers' Register to see whether someone holds a current practising certificate and whether they are authorised to accept instructions directly from the public. In Scotland the equivalent professionals are advocates, regulated through the Faculty of Advocates.",
  "Barristers usually work from chambers, with clerks who manage diaries and fees. Many barristers can be instructed through a solicitor in the traditional way, and those registered under the Public Access scheme can be instructed directly by members of the public for suitable matters.",
 ],
 scenarios=["a written opinion on the strength of a case before going further","representation at a court or tribunal hearing","advice on a family, employment or immigration hearing","help drafting a statement, appeal or skeleton argument","specialist advice in areas such as tax, planning or intellectual property","a second opinion on advice already received","mediation or negotiation support in a dispute","representation in criminal proceedings"],
 prepare=["a short summary of the issue and what you want from the barrister","the court or tribunal involved and any hearing dates","key documents, numbered and in date order","any previous advice you have received","whether you already have a solicitor","what you can do yourself, such as filing papers","your budget expectations, so scope can be agreed","any language or accessibility needs for hearings"],
 questions=["Are you authorised to accept public access instructions for this kind of matter?","What exactly will you do, and what will I need to do myself?","Is the fee fixed for this piece of work?","Who should I contact in chambers about practical questions?","What happens if the hearing is moved or adjourned?","Do I need a solicitor as well for this case?","How much experience do you have before this court or tribunal?","What are the main risks in my position?"],
 fees=["Barristers usually agree a fee for a defined piece of work, such as a written advice, a conference or attendance at a hearing, often negotiated through their clerk. Fees reflect seniority, specialism and the time needed. iComply does not publish fees; the chambers will quote you, POA.","Ask clerks to confirm the fee in writing, what it covers and what happens if the hearing runs longer or is adjourned. Under public access, you may need to handle some administrative tasks a solicitor would normally do."],
 red_flags=["no entry on the Barristers' Register","unclear terms about what the fee covers","no written client care letter for a public access instruction","promises about the outcome of a hearing","pressure to instruct without seeing the papers"],
 timeline="Barristers' diaries can fill weeks ahead, especially for hearings. If you have a fixed hearing date, include it prominently in your enquiry. Written advice on a straightforward point can sometimes be turned round quickly when the papers are well organised.",
 after="Once matched, the barrister or their clerk will review whether the matter is suitable, agree terms and confirm the work in writing. Your professional relationship is with the barrister. iComply does not give legal advice.",
 faqs=[("Can I go straight to a barrister without a solicitor?","Often yes, through the Public Access scheme, if the barrister is registered and the matter is suitable. Some cases still need a solicitor, and the barrister will tell you if so."),("What is the difference between a solicitor and a barrister?","Solicitors usually manage a case from start to finish and deal with clients day to day. Barristers specialise in advocacy and specialist advice, and are typically brought in for hearings or difficult legal questions.")],
)
F['conveyancer'] = dict(
 noun='conveyancer', nouns='conveyancers', practice='conveyancing firm', hub='conveyancers', group='legal',
 regulator=[
  "Conveyancing in England and Wales is a reserved legal activity. It can be carried out by solicitors regulated by the SRA or by licensed conveyancers regulated by the Council for Licensed Conveyancers (CLC). Both must hold professional indemnity insurance and follow strict rules on handling client money. In Scotland, property transactions are handled by solicitors under Scottish law.",
  "Many lenders only work with conveyancers on their panel, and the Law Society's Conveyancing Quality Scheme (CQS) is a common accreditation. Check that your chosen firm is on your lender's panel before you instruct them.",
 ],
 scenarios=["a first-time buyer purchasing with a mortgage","a seller who has accepted an offer and needs a firm quickly","a chain of linked sales and purchases","a leasehold flat with service charges and a lease to review","a remortgage or transfer of equity","a new-build purchase with developer deadlines","a property bought at auction with a short completion deadline","a shared ownership or Help to Buy-style purchase"],
 prepare=["the property address and whether it is freehold or leasehold","whether you are buying, selling or both","the agreed price range and whether you have a mortgage","your lender's name, if you know it","any key dates, such as an exchange or completion target","whether you are in a chain","for leasehold, any information from the managing agent","any planned works, extensions or boundary questions"],
 questions=["Will one named person handle my file?","Are you on my lender's panel?","Is your quote fixed, and what disbursements are extra?","How do you protect me against payment fraud?","How will you update me, and how quickly will you reply?","What searches do you recommend for this property?","How do you handle leasehold management packs?","What happens to the fee if the transaction falls through?"],
 fees=["Conveyancing is often quoted as a fixed legal fee plus disbursements, such as search fees, Land Registry fees and Stamp Duty Land Tax. Leasehold, new-build and auction purchases usually involve more work. Regulated firms in England and Wales must publish pricing information for residential conveyancing. iComply does not set fees; the firm will quote you, POA.","Compare written quotes line by line rather than on the headline figure, and ask whether there is a fee if the deal falls through. Very low quotes sometimes mean higher add-on charges later."],
 red_flags=["bank details sent by email or changed by email (always phone to verify)","quotes that leave out common disbursements","no named person responsible for your file","not being on your lender's panel","slow responses before you have even instructed them"],
 timeline="A typical freehold purchase in England and Wales often takes a few months from offer to completion, and leasehold transactions usually take longer. Auction purchases may require completion within a short, fixed period. Tell us your target dates so we can match you with a firm with the capacity to keep up.",
 after="After the introduction, the firm will send its terms, carry out identity and source-of-funds checks and open your file. From then on they handle the legal work with the other side's conveyancer. iComply does not take part in the transaction or hold any money.",
 faqs=[("When should I instruct a conveyancer?","As soon as your offer is accepted, or before you list a property for sale. Instructing early helps you avoid delays."),("What is the difference between a solicitor and a licensed conveyancer?","Both are regulated and insured. Licensed conveyancers specialise in property transactions, while solicitors can also advise on wider legal issues. Either can handle a standard purchase or sale.")],
)
F['wills'] = dict(
 noun='wills and probate specialist', nouns='wills and probate specialists', practice='wills and probate practice', hub='wills-probate', group='legal',
 regulator=[
  "Writing a will is not a reserved legal activity in England and Wales, so some will writers are not regulated. Solicitors (SRA) and chartered legal executives (CILEx) are regulated, insured and covered by the Legal Ombudsman. Many specialists are also members of STEP (the Society of Trust and Estate Practitioners) or Solicitors for the Elderly. Applying for a grant of probate on someone else's behalf for a fee is a reserved activity.",
  "When choosing a provider, ask whether they are regulated, whether they hold professional indemnity insurance and where your original will is stored. Scotland has its own rules on succession and confirmation, so make sure your adviser practises in the right jurisdiction.",
 ],
 scenarios=["a first will after buying a home or having children","updating a will after marriage, divorce or a new relationship","a blended family with children from different relationships","business owners who need their shares or partnership covered","setting up lasting powers of attorney alongside a will","dealing with the estate of a parent or partner who has died","a dispute about a will or how an estate is being handled","planning for inheritance tax and passing on assets"],
 prepare=["a list of main assets and roughly what they are worth","who you would like to benefit, and anyone you want to exclude","who you would like as executors and guardians","details of any existing will","for an estate: the death certificate and a copy of the will","any property owned jointly, overseas or through a business","pension and life insurance nominations","questions about care costs or inheritance tax"],
 questions=["Are you regulated, and by whom?","Is the fee fixed for the will, or charged by time?","How will you check the will is valid and properly signed?","Where will the original be stored, and is there a charge?","Do you also handle lasting powers of attorney?","For probate, what will you do and what will the executors do?","How do you estimate the cost of administering an estate?","What happens if a family member raises a dispute?"],
 fees=["Simple wills are often offered at a fixed fee, while trusts, business assets and complex families take more time. Estate administration may be charged by time, as a fixed fee for set stages, or occasionally as a percentage of the estate. iComply does not publish fees; the practice will quote you, POA.","Ask for the fee in writing, including storage, VAT and probate court fees. For estate work, ask for an estimate of the total cost and how often you will receive updates."],
 red_flags=["no regulation and no professional indemnity insurance","pressure to buy add-on trusts or storage you do not need","no proper advice about signing and witnessing","percentage fees for estate work without a clear explanation","unwillingness to provide a written estimate"],
 timeline="A straightforward will can often be drafted within a few weeks of the first meeting. Estates take longer: obtaining a grant, collecting assets and paying debts commonly takes many months, more if property must be sold or there is a dispute.",
 after="Once introduced, the practice will take instructions, carry out identity checks and confirm the fee in writing. They are responsible for the legal work. iComply does not draft wills or administer estates.",
 faqs=[("What happens if I die without a will?","The intestacy rules decide who inherits, which may not reflect your wishes, especially for unmarried partners and stepchildren. A will lets you choose."),("Do I need a solicitor for probate?","Not always. Executors can apply for probate themselves for simpler estates. Many choose professional help where there is property, inheritance tax, overseas assets or family tension.")],
)
F['immigration'] = dict(
 noun='immigration adviser', nouns='immigration advisers', practice='immigration practice', hub='immigration-advisors', group='legal',
 regulator=[
  "It is a criminal offence to give immigration advice in the UK unless you are qualified and regulated. Advisers must be registered with the Immigration Advice Authority (IAA, formerly the OISC) at the right level for your matter, or be a solicitor, barrister or chartered legal executive authorised by their own regulator. Check the IAA's adviser finder or the SRA register before you share documents or pay.",
  "IAA advisers are registered at levels that limit what they can do, from basic applications to appeals and representation. Ask what level an adviser holds and whether it covers your type of case.",
 ],
 scenarios=["applying for a skilled worker or other work visa","bringing a spouse, partner or children to the UK","applying for indefinite leave to remain or British citizenship","a student visa or switching from a student visa to work","a refused application and the options for review or appeal","claiming asylum or seeking advice on a protection claim","a business or innovator route for a new venture","visiting the UK for family events or business"],
 prepare=["your current immigration status and visa expiry date","passport and any previous visa or residence permit details","the route you think applies, if you know it","any refusal letters, with dates","your travel and residence history","employer or sponsor details, if relevant","family members involved and their status","any deadlines from the Home Office or a tribunal"],
 questions=["Are you registered with the IAA or authorised by another regulator, and at what level?","Have you handled applications or appeals like mine?","Is your fee fixed, and does it include Home Office fees?","What documents will you need, and in what form?","What are the main risks in my application?","How long is the process likely to take?","What happens if the application is refused?","Who will be my main contact?"],
 fees=["Immigration advisers usually charge a fixed professional fee for a defined application or stage, separate from Home Office fees and the Immigration Health Surcharge, which are paid to the government. Appeals and complex cases cost more. Legal aid is available in some asylum and protection cases. iComply does not publish fees; the adviser quotes you, POA.","Always ask for the fee and what it covers in writing, and keep receipts. Never pay someone who cannot show they are regulated."],
 red_flags=["no IAA registration or other legal regulation","guarantees that a visa will be granted","requests to give false information or documents","pressure to pay large sums in cash","advice given only through messaging apps with no written terms"],
 timeline="Timescales depend on the route and on Home Office processing times, which change. Some routes offer priority services. Appeal and review deadlines are short and strictly applied, so include any deadline at the top of your enquiry.",
 after="Once matched, the adviser will check their regulation covers your case, agree terms and start gathering documents. They are responsible for the advice and any application they submit. iComply does not give immigration advice.",
 faqs=[("Is it safe to use an unregulated immigration adviser?","No. Giving immigration advice without regulation is a criminal offence in the UK, and you may have no protection if something goes wrong. We only introduce regulated advisers."),("Can an adviser speed up my application?","An adviser cannot control Home Office processing times, but a complete, well-prepared application avoids avoidable delays. Some routes have paid priority services.")],
)
F['architect'] = dict(
 noun='architect', nouns='architects', practice='architecture practice', hub='architects', group='property-prof',
 regulator=[
  "\"Architect\" is a protected title in the UK. Only people on the Architects Registration Board (ARB) register can call themselves architects, and they must follow the ARB code of conduct and hold professional indemnity insurance. Many practices are also RIBA Chartered Practices. Architectural designers and technologists can do excellent work too, but they are not registered architects, so it is worth knowing which you are hiring.",
  "Before you appoint anyone, check the ARB register and ask for a written appointment that sets out services, fees and responsibilities. Building regulations approval, planning permission and party wall matters are separate processes that your architect can help you navigate.",
 ],
 scenarios=["a rear or side extension to add space","a loft or garage conversion","a new-build house on a plot","alterations to a listed building or a home in a conservation area","an office, shop or commercial refurbishment","an energy-efficient renovation or eco build","a feasibility study before buying a property","help with a planning application or appeal"],
 prepare=["the property address and whether it is listed or in a conservation area","photos of the existing building and the space you want to change","a rough brief: what you want, why, and must-haves","your budget range for the whole project","any existing drawings, surveys or planning history","your timing hopes, including when you want to start building","whether you need full services or just planning drawings","any neighbours or boundary issues you already know about"],
 questions=["Are you ARB registered?","Can I see similar projects you have completed?","Which RIBA work stages will you cover?","How do you charge: fixed fee, percentage or hourly?","Who will do the drawings and attend site?","How do you handle planning and building regulations?","What other consultants might I need, such as a structural engineer?","How will you help keep the build within budget?"],
 fees=["Architects commonly charge a fixed fee per stage, a percentage of the build cost, or an hourly rate for smaller pieces of work. The scope, from initial sketches to full contract administration, makes a big difference. iComply does not publish fees; the practice will give you a POA proposal.","Ask for a written fee proposal linked to the RIBA stages, and check what is excluded, such as planning fees, surveys and other consultants."],
 red_flags=["using the title \"architect\" without ARB registration","no written appointment or scope of services","unrealistic promises about planning permission","no professional indemnity insurance","reluctance to discuss budget early"],
 timeline="Design and planning usually take several months before building starts. A householder planning application normally has a statutory determination period of around eight weeks once validated, though decisions can take longer. Listed building consent and complex sites take more time.",
 after="After the introduction, the practice will usually arrange a site visit or video call, discuss your brief and send a fee proposal. If you appoint them, your contract is with the practice. iComply does not design buildings or manage projects.",
 faqs=[("Do I need an architect for an extension?","Not legally, but a registered architect brings design skill, planning experience and accountability. For simple work, an architectural technologist or designer may be enough. We can match you to the right level of help."),("Will an architect guarantee planning permission?","No one can guarantee planning permission. A good architect will explain local policy, the risks and how to give your application the best chance.")],
)
F['surveyor'] = dict(
 noun='surveyor', nouns='surveyors', practice='surveying practice', hub='surveyors', group='property-prof',
 regulator=[
  "Many surveyors are members of the Royal Institution of Chartered Surveyors (RICS), and RICS-regulated firms must follow professional standards, hold insurance and offer a complaints process. Chartered surveyors use the letters MRICS or FRICS. Some specialist roles have their own bodies, such as the Faculty of Party Wall Surveyors or the Property Care Association for damp and timber specialists.",
  "Check the RICS directory, ask which report type you are getting and confirm whether the surveyor is independent of the sale. For asbestos work, look for organisations accredited by UKAS for surveying.",
 ],
 scenarios=["a buyer wanting a survey before exchanging contracts","an owner worried about cracks, damp or roof problems","a neighbour planning work that affects a shared wall","a commercial tenant at the end of a lease","a landlord or developer needing cost or measurement advice","a dispute over where a boundary lies","insurance needing an accurate rebuild valuation","a renovation project that needs a building surveyor to oversee work"],
 prepare=["the property address and type","the age of the property, if known","why you need the survey and any deadline","any particular concerns, such as cracks, damp or extensions","access arrangements and who holds the keys","for party wall matters, a description of the planned works","any previous reports or drawings","your lender's requirements, if a mortgage is involved"],
 questions=["Are you RICS regulated or a member of another relevant body?","Which type of survey or report do you recommend, and why?","What will the report cover, and what is excluded?","When can you inspect, and when will I receive the report?","Can I call you to talk through the findings?","Are you independent of the agent or seller?","Do you hold professional indemnity insurance?","What happens if you find something that needs further investigation?"],
 fees=["Survey fees depend on the type of report, the size and age of the property and how far the surveyor must travel. Specialist and commercial work is usually quoted individually. iComply does not publish fees; the surveyor quotes you, POA.","Ask for the scope of the inspection in writing, and check whether follow-up calls or additional investigations are included."],
 red_flags=["a report type that does not match the property's age or condition","links to the selling agent that are not disclosed","no professional indemnity insurance","reluctance to discuss findings after the report","quotes without a clear description of the inspection"],
 timeline="Residential inspections can often be booked within a week or two, with reports following within a few working days. Party wall matters follow statutory notice periods, and specialist investigations may need extra visits.",
 after="Once introduced, the surveyor will confirm terms of engagement before the inspection. The report and professional responsibility for it sit with the surveyor. iComply does not inspect properties.",
 faqs=[("Which survey do I need when buying a home?","For a conventional property in reasonable condition, a RICS Level 2 survey is often enough. Older, larger or altered properties often justify a Level 3 building survey. A surveyor can recommend the right level."),("Is a mortgage valuation the same as a survey?","No. A mortgage valuation is carried out for the lender. A survey is carried out for you and looks at the property's condition.")],
)
