# Modifier sections: (heading variants, paragraphs, faq)
MOD = {
'best': (["How to judge the best choice of {lab}","What \"best\" really means when choosing {lab}","Finding the best {noun}: a practical checklist"],
 ["There is no single best {noun} for everyone. The right choice depends on your situation, how complex it is, where you are and how you like to communicate. A practice that is outstanding for one client can be a poor fit for another.",
  "Useful signs of quality include verified registration with the right body, relevant experience with situations like yours, clear written terms, honest answers about risks, and good communication from the very first contact. Online reviews can help, but read them for patterns rather than single comments, and remember that the most visible firm is not always the most suitable.",
  "When we match you, we look at fit rather than marketing claims: specialism, location, capacity and whether the practice can start when you need it."],
 ("How do you decide which {noun} is best for me?","We look at what you need, where you are, how urgent it is and which practices have the relevant experience and capacity. We do not rank firms by who pays the most; we aim for the best fit for your brief.")),
'top': (["What sets a top {noun} apart","Choosing a top-rated {noun}","Top {nouns}: looking beyond rankings"],
 ["\"Top\" lists online are often based on advertising spend or a handful of reviews. A genuinely top {noun} for your needs combines proper qualifications, a strong track record in your type of matter and the time to give your case attention.",
  "Ask about experience with situations like yours, who will actually do the work and how they will keep you updated. A top practice will be comfortable answering these questions and will explain fees clearly before you commit.",
  "We use these same questions when matching, so you are introduced to practices that are strong for your specific brief rather than simply prominent."],
 ("Are the practices you introduce top-rated?","We introduce practices that are properly registered and suitable for your brief. Ratings are one input, but fit, experience and capacity matter more than a position in an online list.")),
'cheap': (["Keeping costs down without cutting corners","Low-cost options: what to watch for","Getting good value from {lab}"],
 ["It is sensible to want good value, and many people can keep costs down by being clear about what they need. A short, well-organised brief and tidy paperwork usually reduce the time a professional has to spend.",
  "Be careful with the lowest headline price. Check what is included, what counts as extra work and whether the provider is properly registered and insured. A cheap quote that leaves out essential steps can end up costing more.",
  "iComply does not set fees. Every practice quotes POA, and you are free to compare written quotes before deciding."],
 ("Can you find me a cheap {noun}?","We can match you with practices whose scope suits your budget, and you can compare quotes. We will not introduce unregistered providers to hit a low price.")),
'affordable': (["Affordable help: getting the scope right","How to make {lab} more affordable","Planning an affordable route"],
 ["Affordability usually comes from scope rather than from finding the lowest rate. Being clear about what you need, and what you can do yourself, helps a professional quote fairly.",
  "Ask whether fixed fees, staged work or payment plans are available, and whether any insurance, membership or public funding might cover part of the cost. Compare written quotes like for like, including any extras.",
  "Tell us your budget expectations in your enquiry. We match you with practices that can work within a sensible scope, and quotes remain POA from the practice."],
 ("How can I keep the cost affordable?","Share a clear brief, gather your documents and ask for a written scope. Fixed fees for defined stages can help you plan.")),
'local': (["Using a local {noun}","Why a local {noun} can help","Local {nouns} and when distance matters"],
 ["Some people prefer a {noun} they can visit in person, who knows the area and can meet face to face when needed. For other matters, distance makes little difference because most of the work happens by phone, email and video.",
  "When you enquire, tell us your town or postcode and how far you are happy to travel. We look for practices with capacity near you, and we will say honestly if the closest suitable option is further away or works remotely.",
  "Local knowledge can be valuable where regional rules, local services or in-person appointments play a part."],
 ("Will I be matched with someone local?","Where possible, yes. Tell us your town or postcode and travel preferences. If a better-suited practice works remotely or a little further away, we will explain why.")),
'online': (["Using {lab} online","How online appointments work","Online or in person: pros and cons"],
 ["Many professionals now work online, using video calls, secure portals and electronic signatures. This can save travel time, widen your choice and make evening or early appointments easier.",
  "Online services still need the same checks: registration, insurance, clear terms and secure handling of your documents. Some parts of the work may still need an in-person visit, such as examinations or signing certain documents.",
  "Tell us whether you prefer online, in person or a mix, and we will match you accordingly."],
 ("Can everything be done online?","Often much of it can. Some steps may need a visit, depending on the service. The practice will tell you what can be done remotely.")),
'accredited': (["Accreditation: what to check","What accreditation means when choosing {lab}","Checking accreditation before you choose"],
 ["Accreditation means a practice or professional has met standards set by a regulator or professional body. It is worth checking both the individual's registration and any practice-level accreditation, as they cover different things.",
  "Ask which accreditations apply, what they require and how you can verify them online. Accreditation is not a guarantee of the outcome, but it does mean there are standards, a code of conduct and a route for complaints.",
  "iComply itself is not an accrediting body. We introduce practices that hold the registration their profession requires, and we encourage you to check it yourself."],
 ("Is iComply accredited?","iComply is a matching service, not a regulator or accrediting body. The professionals we introduce hold their own registrations, which you can check on the relevant public register.")),
'comparison': (["Comparing {nouns} side by side","How to compare quotes fairly","Making a fair comparison"],
 ["Comparing professionals works best when you compare like with like. Ask each practice for a written scope, timescale and fee basis, then check what is included and excluded.",
  "Look beyond price: experience with your type of matter, who will do the work, communication and registration all matter. A short comparison table of these points can make the decision much clearer.",
  "We can introduce more than one suitable practice where capacity allows, so you can compare quotes. Quotes are POA from each practice."],
 ("Can I get more than one quote?","Yes, where capacity allows. Tell us if you want to compare and we will try to introduce more than one suitable practice.")),
'mobile': (["Mobile and visiting {nouns}","When a {noun} can come to you","Home and on-site visits"],
 ["Some professionals offer home, workplace or on-site visits, which can help if travel is difficult, time is short or the work itself needs to happen where you are.",
  "Visiting services may have a smaller coverage area or charge for travel, so ask about the area covered and any visit fees. Some parts of the work may still need a clinic, office or specialist equipment.",
  "Mention in your enquiry that you need a visit, and we will look for practices that can come to you."],
 ("Can the professional come to me?","Some can. Tell us your location and needs, and we will match you with practices offering visits where available.")),
'nationwide': (["Nationwide options for {lab}","Using a {noun} anywhere in the UK","National coverage, local fit"],
 ["Many professionals work across the UK, especially where most of the work can be done remotely. Others are best chosen locally. The right approach depends on what you need.",
  "Remember that some services differ between England, Wales, Scotland and Northern Ireland, with different laws, regulators or processes. Make sure your professional works in the right part of the UK for your matter.",
  "We take enquiries from across the UK and match on fit, jurisdiction and capacity."],
 ("Do you cover the whole UK?","We accept enquiries UK-wide. Matches depend on specialism and capacity, and on the right jurisdiction for your matter.")),
'packages': (["Packages and fixed-scope options","Understanding packages for {lab}","What a package should include"],
 ["Packages bundle a defined set of services for a set fee, which can make costs more predictable. They work well when your needs are straightforward and clearly defined.",
  "Read package terms closely. Check what is included, what triggers extra charges, and what happens if your situation turns out to be more complex. Compare packages from different practices on scope, not just on headline price.",
  "Quotes and package terms come from the practice and are POA. We help you reach practices whose packages fit your brief."],
 ("Are packages better value?","They can be, if the scope matches what you need. Check exclusions and extra-work charges before you sign.")),
'consultation': (["Your first consultation","What happens in a first consultation","Making the most of an initial consultation"],
 ["A first consultation is a chance to explain your situation, hear initial views and decide whether you want to go ahead. Some practices offer a short free call; others charge for a longer first meeting.",
  "Prepare a short summary, key dates and documents, and a list of questions. Ask about next steps, likely costs and timescales. You are not committed to anything by attending a consultation.",
  "We can arrange an introduction so you can book a consultation with a suitable practice."],
 ("Is the first consultation free?","It depends on the practice. Some offer a free initial call; others charge. The practice will tell you before you book.")),
'rated': (["Choosing a well-rated {noun}","Reading reviews of {nouns}","Ratings: useful but not the whole story"],
 ["Ratings and reviews can show how a practice treats clients, especially around communication and reliability. Look for consistent themes across many reviews rather than a single glowing or harsh comment.",
  "Combine reviews with objective checks: registration, relevant experience and clear written terms. Some professions also publish inspection ratings, which are a more structured guide than online star ratings.",
  "We look for well-regarded practices that suit your brief, but always check registers and terms yourself before instructing."],
 ("Do you only introduce highly rated practices?","We introduce properly registered practices that suit your brief. Reputation is one factor alongside fit, experience and capacity.")),
'fast': (["Getting {lab} quickly","How to speed things up","Fast service without cutting corners"],
 ["Speed often depends on you as much as the professional. Having documents ready, replying quickly and being clear about deadlines all help.",
  "Ask the practice about current capacity and realistic timescales before you instruct. Be wary of promises that ignore steps that take time, such as third-party checks or regulator processing.",
  "Tell us your deadline. We prioritise practices that can start promptly."],
 ("How fast can you match me?","Straightforward enquiries are usually reviewed within a few working days. Urgent matters should be marked clearly.")),
'fixed-fee': (["Fixed fees and {lab}","How fixed fees work","What a fixed fee should cover"],
 ["Fixed fees give certainty: you know the cost of a defined piece of work in advance. They suit straightforward matters with a predictable scope.",
  "Ask exactly what the fixed fee covers, what counts as extra work and how extras are priced. Third-party costs, such as government or search fees, are usually separate.",
  "Fees are set by the practice and are POA. We can match you with practices that offer fixed-fee options where they suit your matter."],
 ("Is everything included in a fixed fee?","Usually not third-party costs or unexpected extra work. Ask for a written list of inclusions and exclusions.")),
}
FORM = {
 'near': (["Finding {lab} near you","Near me: how local matching works","Looking for {lab} close to home"],
  ["When you search for {lab} near you, you usually want someone reachable, available and trustworthy. Tell us your town or postcode and we look for suitable practices nearby with capacity to help.",
   "Near-me searches return lots of results, from directories to adverts. Our role is simpler: understand your brief and introduce a suitable professional, so you do not have to work through the list alone."]),
 'bare': (["What {lab} does","What to know before you contact anyone","The basics of {lab}"],
  ["If you have not used {lab} before, it helps to understand what the work involves before you contact anyone. That makes your first conversation more productive and helps you spot good advice.",
   "Once you know what you need, we can match you with a suitable practice. You do not need to know every detail; a short description is enough to start."]),
 'plural': (["Comparing {nouns}","How {nouns} differ","Choosing between {nouns}"],
  ["{Nouns} vary in specialism, size, fees and approach. Some focus on particular types of client; others offer a broad service. Knowing the differences helps you choose.",
   "Rather than searching through long lists of {nouns}, tell us what you need. We introduce practices that fit, and you can compare their quotes."]),
}
ROLE = {
 'advisor': "Adviser and advisor are simply two spellings of the same word. What matters is whether the person giving advice is qualified and, where the law requires it, regulated for that type of advice.",
 'consultant': "\"Consultant\" is a broad title that anyone can use. Check what qualifications and registrations sit behind it, and whether the work you need is regulated.",
 'specialist': "A specialist should be able to show focused experience in the area, such as qualifications, memberships or a track record of similar cases. Ask what proportion of their work is in this area.",
 'help': "Getting help early often makes a matter simpler and cheaper to resolve. You do not need to have everything worked out before you enquire.",
 'broker': "A broker works on your behalf to find suitable products from providers. Ask how many providers they compare and how they are paid.",
 'clinic': "Clinics vary from single-practitioner rooms to multi-specialist centres. Ask who will see you, their registration and what facilities are on site.",
 'lawyers': "\"Lawyer\" is a general term. In England and Wales the person handling your matter will usually be a solicitor, chartered legal executive or barrister, each regulated by their own body.",
 'therapist': "\"Therapist\" covers many approaches. Ask about training, which register they are on and the type of therapy they offer.",
}
